const actionTypes = {
  ACTIVE_PAGE_NUMBER: 'ACTIVE_PAGE_NUMBER',
  GRID_COLUMNS_FORMULA: 'GRID_COLUMNS_FORMULA',
  IS_BRIEF_RESULTS: 'IS_BRIEF_RESULTS',
  NUM_RESULTS: 'NUM_RESULTS',
  PREV_PAGE_PATH: 'PREV_PAGE_PATH',
  RESULTS_2D: 'RESULTS_2D',
  SCROLL_TOP_ARR: 'SCROLL_TOP_ARR',
  STATUSES: 'STATUSES',
  VALID_PROPERTIES: 'VALID_PROPERTIES',
};

export default actionTypes;